from datetime import datetime, timezone
from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field, ConfigDict

class UnifiedSignal(BaseModel):
    """
    Normalized data contract representing an incoming disaster intelligence signal
    from any external connector (SACHET, GDACS, NASA FIRMS, USGS) or ResQFusion Citizen reports.
    """
    model_config = ConfigDict(from_attributes=True)

    external_id: str = Field(..., description="Unique provider ID or deterministic hash")
    source: str = Field(..., description="E.g. SACHET, GDACS, NASA_FIRMS, USGS, RESQFUSION_CITIZEN")
    source_type: str = Field(..., description="E.g. official_india_alert, official_global, satellite_fire, earthquake, citizen_report")
    event_type: str = Field(..., description="E.g. Flood, Cyclone, Earthquake, Fire, Infrastructure, Tsunami")
    title: str = Field(..., description="Headline or concise event summary")
    description: str = Field(..., description="Detailed textual description or raw narrative")
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), description="Event detection or issuance timestamp")
    latitude: float = Field(..., ge=-90.0, le=90.0, description="WGS84 Latitude")
    longitude: float = Field(..., ge=-180.0, le=180.0, description="WGS84 Longitude")
    
    # Optional / Source-dependent Fields (no artificial invention)
    severity: str = Field(default="medium", description="critical, high, medium, low, or unknown")
    urgency: Optional[str] = Field(default=None, description="Immediate, Expected, Future, Past, Unknown")
    certainty: Optional[str] = Field(default=None, description="Observed, Likely, Possible, Unlikely, Unknown")
    confidence: float = Field(default=0.8, ge=0.0, le=1.0, description="Source reliability / detection confidence")
    
    people_affected: Optional[int] = Field(default=None, description="Null if unknown; only populated when evidence exists")
    medical_need: Optional[bool] = Field(default=None, description="Null if unknown")
    resource_requirements: List[str] = Field(default_factory=list, description="Isolated physical/logistical emergency resource requests")
    
    is_near_real_time: bool = Field(default=False, description="True for satellite sensor detections such as NASA FIRMS")
    is_demo: bool = Field(default=False, description="True if generated by offline fallback / demo fixture")
    
    raw_data: Dict[str, Any] = Field(default_factory=dict, description="Original unparsed payload from external provider")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Extra provider attributes (FRP, depth, magnitude, alert level, etc.)")
